services:
  - type: web
    name: my-building-portal
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: SENDGRID_API_KEY
        sync: false
      - key: SENDGRID_FROM
        sync: false
      - key: FIREBASE_URL
        sync: false
      - key: FIREBASE_SERVICE_ACCOUNT
        sync: false
      - key: FIREBASE_STORAGE_BUCKET
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: BASE_URL
        sync: false
      - key: MANAGER_EMAIL
        sync: false
      - key: PORT
        value: 3000