const PDFDocument = require('pdfkit');
const { storage } = require('../config/firebase');

async function generateApplicationPDF(app) {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ margin: 50, size: 'A4' });
      const chunks = [];

      doc.on('data', chunk => chunks.push(chunk));
      doc.on('end', async () => {
        try {
          const buffer = Buffer.concat(chunks);
          const fileName = `pdfs/${app.buildingKey}/${app.ref}-${Date.now()}.pdf`;
          const bucket = storage.bucket();
          const file = bucket.file(fileName);

          await file.save(buffer, {
            metadata: { contentType: 'application/pdf' },
            public: true
          });

          const url = `https://firebasestorage.googleapis.com/v0/b/${bucket.name}/o/${encodeURIComponent(fileName)}?alt=media`;
          console.log('PDF generated:', url);
          resolve(url);
        } catch (err) {
          console.error('PDF upload failed:', err.message);
          resolve(null);
        }
      });

      const NAVY = '#1a3a5c';
      const GOLD = '#c4a038';
      const GREY = '#5a6478';
      const LIGHT = '#f4f5f7';

      // ─── PAGE 1: COVER ───
      doc.rect(0, 0, doc.page.width, 120).fill(NAVY);
      doc.fillColor('#fff').font('Helvetica-Bold').fontSize(22).text('My Building Portal', 50, 35);
      doc.fillColor(GOLD).font('Helvetica').fontSize(11).text('Queensland Body Corporate Management', 50, 62);
      doc.fillColor('#fff').font('Helvetica').fontSize(10).text('Application Record', 50, 80);

      doc.moveDown(4);
      doc.fillColor(NAVY).font('Helvetica-Bold').fontSize(16).text('APPLICATION RECORD', { align: 'center' });
      doc.moveDown(0.5);

      const outcome = app.outcome || app.status;
      const outcomeColor = outcome === 'approved' ? '#2d9e5c' : outcome === 'rejected' ? '#d84a30' : '#c4a038';
      doc.fillColor(outcomeColor).font('Helvetica-Bold').fontSize(20).text(outcome.toUpperCase(), { align: 'center' });

      doc.moveDown(1);
      doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke(LIGHT);
      doc.moveDown(0.5);

      const meta = [
        ['Building', app.building],
        ['Address', app.committeeSnapshot && app.committeeSnapshot.address || ''],
        ['Lot Number', app.lot],
        ['Application Type', app.formLabel],
        ['Reference Number', app.ref],
        ['Submitted By', app.submittedByName || 'Unknown'],
        ['Submitted At', new Date(app.submittedAt).toLocaleString('en-AU', { timeZone: 'Australia/Brisbane' })],
        ['Finalized At', app.auditSnapshot ? new Date(app.auditSnapshot.finalizedAt).toLocaleString('en-AU', { timeZone: 'Australia/Brisbane' }) : 'N/A'],
        ['Outcome', outcome.toUpperCase()]
      ];

      meta.forEach(([label, value]) => {
        if (!value) return;
        doc.fillColor(GREY).font('Helvetica').fontSize(10).text(label + ':', 50, doc.y, { continued: true, width: 160 });
        doc.fillColor(NAVY).font('Helvetica-Bold').text(' ' + value);
        doc.moveDown(0.3);
      });

      doc.moveDown(2);
      doc.fillColor(GREY).font('Helvetica').fontSize(8)
        .text('Generated by My Building Portal. Record retained pursuant to s206 Body Corporate and Community Management Act 1997 (QLD).', 50, doc.page.height - 60, { align: 'center', width: 495 });

      // ─── PAGE 2: APPLICATION DETAILS ───
      doc.addPage();
      sectionHeader(doc, 'APPLICATION DETAILS', NAVY);

      if (app.formData) {
        Object.entries(app.formData).forEach(([key, value]) => {
          if (!value) return;
          const label = key.replace(/([A-Z])/g, ' $1').replace(/^./, s => s.toUpperCase());
          doc.fillColor(GREY).font('Helvetica').fontSize(9).text(label + ':', { continued: true });
          doc.fillColor(NAVY).font('Helvetica').fontSize(9).text('  ' + String(value));
          doc.moveDown(0.3);
        });
      }

      // ─── PAGE 3: INFO THREAD (if any) ───
      const infoThread = app.auditSnapshot && app.auditSnapshot.infoThread;
      if (infoThread && infoThread.length > 0) {
        doc.addPage();
        sectionHeader(doc, 'INFORMATION EXCHANGE', NAVY);

        infoThread.forEach(entry => {
          const typeLabel = entry.type === 'question' ? 'QUESTION' : entry.type === 'addendum' ? 'ADDITIONAL QUESTION' : 'APPLICANT RESPONSE';
          const typeColor = entry.type === 'response' ? '#2d9e5c' : GOLD;
          doc.fillColor(typeColor).font('Helvetica-Bold').fontSize(9).text(typeLabel);
          doc.fillColor(GREY).font('Helvetica').fontSize(8).text(
            `${entry.memberName} · ${new Date(entry.timestamp).toLocaleString('en-AU', { timeZone: 'Australia/Brisbane' })}`
          );
          doc.fillColor(NAVY).font('Helvetica').fontSize(10).text(entry.content);
          doc.moveDown(0.8);
          doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke('#e2e5ea');
          doc.moveDown(0.5);
        });
      }

      // ─── PAGE 4: VOTING AUDIT ───
      doc.addPage();
      sectionHeader(doc, 'VOTING AUDIT TRAIL', NAVY);

      if (app.auditSnapshot) {
        const snap = app.auditSnapshot;
        doc.fillColor(GREY).font('Helvetica').fontSize(10)
          .text(`Total eligible voters: ${snap.totalEligible}   |   Required to pass: ${snap.requiredVotes}   |   Outcome: ${snap.outcome.toUpperCase()}`);
        doc.moveDown(1);

        if (snap.voteBreakdown) {
          snap.voteBreakdown.forEach(v => {
            const voteColor = v.vote === 'approve' ? '#2d9e5c' : v.vote === 'reject' ? '#d84a30' : v.vote === 'info' ? GOLD : GREY;
            doc.fillColor(NAVY).font('Helvetica-Bold').fontSize(10).text(v.memberName, { continued: true });
            doc.fillColor(GREY).font('Helvetica').fontSize(9).text(`  <${v.memberEmail}>`);
            doc.fillColor(voteColor).font('Helvetica-Bold').fontSize(10).text(v.vote ? v.vote.toUpperCase() : 'DID NOT VOTE');
            if (v.votedAt) {
              doc.fillColor(GREY).font('Helvetica').fontSize(8).text(`Voted: ${new Date(v.votedAt).toLocaleString('en-AU', { timeZone: 'Australia/Brisbane' })}`);
            }
            if (v.changedFrom) {
              doc.fillColor(GOLD).font('Helvetica').fontSize(8).text(`Changed from: ${v.changedFrom} at ${new Date(v.changedAt).toLocaleString('en-AU', { timeZone: 'Australia/Brisbane' })}`);
            }
            doc.moveDown(0.5);
          });
        }
      }

      doc.moveDown(2);
      doc.fillColor(GREY).font('Helvetica').fontSize(8)
        .text('This document constitutes an official body corporate voting record. Generated by My Building Portal pursuant to s206 BCCM Act 1997 (QLD). This record is uneditable and retained for a minimum of 7 years.', { align: 'center' });

      doc.end();

    } catch (err) {
      reject(err);
    }
  });
}

function sectionHeader(doc, title, color) {
  doc.rect(50, doc.y, 495, 28).fill(color);
  doc.fillColor('#fff').font('Helvetica-Bold').fontSize(11).text(title, 58, doc.y - 20);
  doc.moveDown(1.5);
}

module.exports = { generateApplicationPDF };